* 21.02.21 ¢¥à­ãâì ¬ áá¨¢ ””Œ‘ O001.xml
function getO001()
  static _O001 := {}
  Local dbName, dbAlias := 'O001'
  local tmp_select := select()


  // O001.dbf - ¡é¥à®áá¨©áª¨© ª« áá¨ä¨ª â®à áâà ­ ¬¨à  (Š‘Œ)
  //  1 - NAME11(C)  2 - KOD(C)  3 - DATEBEG(D)  4 - DATEEND(D)  5 - ALFA2(C)  6 - ALFA3(C)  7 - NAME11(C)
  if len(_O001) == 0
    dbName := '_mo_O001'
    tmp_select := select()
    dbUseArea( .t., "DBFNTX", exe_dir + dbName, dbAlias , .t., .f. )

    (dbAlias)->(dbGoTop())
    do while !(dbAlias)->(EOF())
        aadd(_O001, { alltrim((dbAlias)->NAME11), (dbAlias)->KOD, (dbAlias)->DATEBEG, (dbAlias)->DATEEND, (dbAlias)->ALFA2, (dbAlias)->ALFA3, alltrim((dbAlias)->NAME12) })
        (dbAlias)->(dbSkip())
    enddo
    (dbAlias)->(dbCloseArea())
    Select(tmp_select)


  //   aadd(_O001, {"€”ƒ€ˆ‘’€","004",stod(""),stod(""),"AF","AFG"})
  //   aadd(_O001, {"€‹€ˆŸ","008",stod(""),stod(""),"AL","ALB"})
  //   aadd(_O001, {"€’€Š’ˆ„€","010",stod(""),stod(""),"AQ","ATA"})
  //   aadd(_O001, {"€‹†ˆ","012",stod(""),stod(""),"DZ","DZA"})
  //   aadd(_O001, {"€Œ…ˆŠ€‘Š… ‘€Œ€","016",stod(""),stod(""),"AS","ASM"})
  //   aadd(_O001, {"€„€","020",stod(""),stod(""),"AD","AND"})
  //   aadd(_O001, {"€ƒ‹€","024",stod(""),stod(""),"AO","AGO"})
  //   aadd(_O001, {"€’ˆƒ“€ ˆ €“„€","028",stod(""),stod(""),"AG","ATG"})
  //   aadd(_O001, {"€‡…€‰„†€","031",stod(""),stod(""),"AZ","AZE"})
  //   aadd(_O001, {"€ƒ…’ˆ€","032",stod(""),stod(""),"AR","ARG"})
  //   aadd(_O001, {"€‚‘’€‹ˆŸ","036",stod(""),stod(""),"AU","AUS"})
  //   aadd(_O001, {"€‚‘’ˆŸ","040",stod(""),stod(""),"AT","AUT"})
  //   aadd(_O001, {"€ƒ€Œ›","044",stod(""),stod(""),"BS","BHS"})
  //   aadd(_O001, {"€•…‰","048",stod(""),stod(""),"BH","BHR"})
  //   aadd(_O001, {"€ƒ‹€„…˜","050",stod(""),stod(""),"BD","BGD"})
  //   aadd(_O001, {"€Œ…ˆŸ","051",stod(""),stod(""),"AM","ARM"})
  // aadd(_O001, {"€€„‘","052",stod(""),stod(""),"BB","BRB"})
  // aadd(_O001, {"…‹œƒˆŸ","056",stod(""),stod(""),"BE","BEL"})
  // aadd(_O001, {"…Œ“„›","060",stod(""),stod(""),"BM","BMU"})
  // aadd(_O001, {"“’€","064",stod(""),stod(""),"BT","BTN"})
  // aadd(_O001, {"‹ˆ‚ˆŸ, Œƒ€–ˆ€‹œ… ƒ‘“„€‘’‚","068",stod(""),stod(""),"BO","BOL"})
  // aadd(_O001, {"‘ˆŸ ˆ ƒ…–…ƒ‚ˆ€","070",stod(""),stod(""),"BA","BIH"})
  // aadd(_O001, {"’‘‚€€","072",stod(""),stod(""),"BW","BWA"})
  // aadd(_O001, {"‘’‚ “‚…","074",stod(""),stod(""),"BV","BVT"})
  // aadd(_O001, {"€‡ˆ‹ˆŸ","076",stod(""),stod(""),"BR","BRA"})
  // aadd(_O001, {"…‹ˆ‡","084",stod(""),stod(""),"BZ","BLZ"})
  // aadd(_O001, {"ˆ’€‘Š€Ÿ ’…ˆ’ˆŸ ‚ ˆ„ˆ‰‘ŠŒ Š…€…","086",stod(""),stod(""),"IO","IOT"})
  // aadd(_O001, {"‘‹Œ‚› ‘’‚€","090",stod(""),stod(""),"SB","SLB"})
  // aadd(_O001, {"‚ˆƒˆ‘Šˆ… ‘’‚€, ˆ’€‘Šˆ…","092",stod(""),stod(""),"VG","VGB"})
  // aadd(_O001, {"“…‰-„€“‘‘€‹€Œ","096",stod(""),stod(""),"BN","BRN"})
  // aadd(_O001, {"‹ƒ€ˆŸ","100",stod(""),stod(""),"BG","BGR"})
  // aadd(_O001, {"ŒœŸŒ€","104",stod(""),stod(""),"MM","MMR"})
  // aadd(_O001, {"““„ˆ","108",stod(""),stod(""),"BI","BDI"})
  // aadd(_O001, {"…‹€“‘œ","112",stod(""),stod(""),"BY","BLR"})
  // aadd(_O001, {"Š€Œ„†€","116",stod(""),stod(""),"KH","KHM"})
  // aadd(_O001, {"Š€Œ…“","120",stod(""),stod(""),"CM","CMR"})
  // aadd(_O001, {"Š€€„€","124",stod(""),stod(""),"CA","CAN"})
  // aadd(_O001, {"Š€-‚…„…","132",stod(""),stod(""),"CV","CPV"})
  // aadd(_O001, {"‘’‚€ Š€‰Œ€","136",stod(""),stod(""),"KY","CYM"})
  // aadd(_O001, {"–…’€‹œ-€”ˆŠ€‘Š€Ÿ …‘“‹ˆŠ€","140",stod(""),stod(""),"CF","CAF"})
  // aadd(_O001, {"˜ˆ-‹€Š€","144",stod(""),stod(""),"LK","LKA"})
  // aadd(_O001, {"—€„","148",stod(""),stod(""),"TD","TCD"})
  // aadd(_O001, {"—ˆ‹ˆ","152",stod(""),stod(""),"CL","CHL"})
  // aadd(_O001, {"Šˆ’€‰","156",stod(""),stod(""),"CN","CHN"})
  // aadd(_O001, {"’€‰‚€œ (Šˆ’€‰)","158",stod(""),stod(""),"TW","TWN"})
  // aadd(_O001, {"‘’‚ †„…‘’‚€","162",stod(""),stod(""),"CX","CXR"})
  // aadd(_O001, {"ŠŠ‘‚›… (Šˆ‹ˆƒ) ‘’‚€","166",stod(""),stod(""),"CC","CCK"})
  // aadd(_O001, {"Š‹“ŒˆŸ","170",stod(""),stod(""),"CO","COL"})
  // aadd(_O001, {"ŠŒ›","174",stod(""),stod(""),"KM","COM"})
  // aadd(_O001, {"Œ€‰’’€","175",stod(""),stod(""),"YT","MYT"})
  // aadd(_O001, {"Šƒ","178",stod(""),stod(""),"CG","COG"})
  // aadd(_O001, {"Šƒ, „…ŒŠ€’ˆ—…‘Š€Ÿ …‘“‹ˆŠ€","180",stod(""),stod(""),"CD","COD"})
  // aadd(_O001, {"‘’‚€ Š“Š€","184",stod(""),stod(""),"CK","COK"})
  // aadd(_O001, {"Š‘’€-ˆŠ€","188",stod(""),stod(""),"CR","CRI"})
  // aadd(_O001, {"•‚€’ˆŸ","191",stod(""),stod(""),"HR","HRV"})
  // aadd(_O001, {"Š“€","192",stod(""),stod(""),"CU","CUB"})
  // aadd(_O001, {"Šˆ","196",stod(""),stod(""),"CY","CYP"})
  // aadd(_O001, {"—…˜‘Š€Ÿ …‘“‹ˆŠ€","203",stod(""),stod(""),"CZ","CZE"})
  // aadd(_O001, {"…ˆ","204",stod(""),stod(""),"BJ","BEN"})
  // aadd(_O001, {"„€ˆŸ","208",stod(""),stod(""),"DK","DNK"})
  // aadd(_O001, {"„ŒˆˆŠ€","212",stod(""),stod(""),"DM","DMA"})
  // aadd(_O001, {"„ŒˆˆŠ€‘Š€Ÿ …‘“‹ˆŠ€","214",stod(""),stod(""),"DO","DOM"})
  // aadd(_O001, {"Š‚€„","218",stod(""),stod(""),"EC","ECU"})
  // aadd(_O001, {"‹œ-‘€‹œ‚€„","222",stod(""),stod(""),"SV","SLV"})
  // aadd(_O001, {"Š‚€’ˆ€‹œ€Ÿ ƒ‚ˆ…Ÿ","226",stod(""),stod(""),"GQ","GNQ"})
  // aadd(_O001, {"”ˆˆŸ","231",stod(""),stod(""),"ET","ETH"})
  // aadd(_O001, {"ˆ’…Ÿ","232",stod(""),stod(""),"ER","ERI"})
  // aadd(_O001, {"‘’ˆŸ","233",stod(""),stod(""),"EE","EST"})
  // aadd(_O001, {"”€…‘Šˆ… ‘’‚€","234",stod(""),stod(""),"FO","FRO"})
  // aadd(_O001, {"”‹Š‹…„‘Šˆ… ‘’‚€ (Œ€‹œ‚ˆ‘Šˆ…)","238",stod(""),stod(""),"FK","FLK"})
  // aadd(_O001, {"†€Ÿ „†„†ˆŸ ˆ †›… ‘€„‚ˆ—…‚› ‘’‚€","239",stod(""),stod(""),"GS","SGS"})
  // aadd(_O001, {"”ˆ„†ˆ","242",stod(""),stod(""),"FJ","FJI"})
  // aadd(_O001, {"”ˆ‹Ÿ„ˆŸ","246",stod(""),stod(""),"FI","FIN"})
  // aadd(_O001, {"‹€„‘Šˆ… ‘’‚€","248",stod(""),stod(""),"AX","ALA"})
  // aadd(_O001, {"”€–ˆŸ","250",stod(""),stod(""),"FR","FRA"})
  // aadd(_O001, {"”€–“‡‘Š€Ÿ ƒ‚ˆ€€","254",stod(""),stod(""),"GF","GUF"})
  // aadd(_O001, {"”€–“‡‘Š€Ÿ ‹ˆ…‡ˆŸ","258",stod(""),stod(""),"PF","PYF"})
  // aadd(_O001, {"”€–“‡‘Šˆ… †›… ’…ˆ’ˆˆ","260",stod(""),stod(""),"TF","ATF"})
  // aadd(_O001, {"„†ˆ“’ˆ","262",stod(""),stod(""),"DJ","DJI"})
  // aadd(_O001, {"ƒ€","266",stod(""),stod(""),"GA","GAB"})
  // aadd(_O001, {"ƒ“‡ˆŸ","268",stod(""),stod(""),"GE","GEO"})
  // aadd(_O001, {"ƒ€ŒˆŸ","270",stod(""),stod(""),"GM","GMB"})
  // aadd(_O001, {"€‹…‘’ˆ‘Š€Ÿ ’…ˆ’ˆŸ, ŠŠ“ˆ‚€€Ÿ","275",stod(""),stod(""),"PS","PSE"})
  // aadd(_O001, {"ƒ…Œ€ˆŸ","276",stod(""),stod(""),"DE","DEU"})
  // aadd(_O001, {"ƒ€€","288",stod(""),stod(""),"GH","GHA"})
  // aadd(_O001, {"ƒˆ€‹’€","292",stod(""),stod(""),"GI","GIB"})
  // aadd(_O001, {"Šˆˆ€’ˆ","296",stod(""),stod(""),"KI","KIR"})
  // aadd(_O001, {"ƒ…–ˆŸ","300",stod(""),stod(""),"GR","GRC"})
  // aadd(_O001, {"ƒ…‹€„ˆŸ","304",stod(""),stod(""),"GL","GRL"})
  // aadd(_O001, {"ƒ…€„€","308",stod(""),stod(""),"GD","GRD"})
  // aadd(_O001, {"ƒ‚€„…‹“€","312",stod(""),stod(""),"GP","GLP"})
  // aadd(_O001, {"ƒ“€Œ","316",stod(""),stod(""),"GU","GUM"})
  // aadd(_O001, {"ƒ‚€’…Œ€‹€","320",stod(""),stod(""),"GT","GTM"})
  // aadd(_O001, {"ƒ‚ˆ…Ÿ","324",stod(""),stod(""),"GN","GIN"})
  // aadd(_O001, {"ƒ€‰€€","328",stod(""),stod(""),"GY","GUY"})
  // aadd(_O001, {"ƒ€ˆ’ˆ","332",stod(""),stod(""),"HT","HTI"})
  // aadd(_O001, {"‘’‚ •…„ ˆ ‘’‚€ Œ€Š„€‹œ„","334",stod(""),stod(""),"HM","HMD"})
  // aadd(_O001, {"€‘Šˆ‰ …‘’‹ (ƒ‘“„€‘’‚-ƒ„ ‚€’ˆŠ€)","336",stod(""),stod(""),"VA","VAT"})
  // aadd(_O001, {"ƒ„“€‘","340",stod(""),stod(""),"HN","HND"})
  // aadd(_O001, {"ƒŠƒ","344",stod(""),stod(""),"HK","HKG"})
  // aadd(_O001, {"‚…ƒˆŸ","348",stod(""),stod(""),"HU","HUN"})
  // aadd(_O001, {"ˆ‘‹€„ˆŸ","352",stod(""),stod(""),"IS","ISL"})
  // aadd(_O001, {"ˆ„ˆŸ","356",stod(""),stod(""),"IN","IND"})
  // aadd(_O001, {"ˆ„…‡ˆŸ","360",stod(""),stod(""),"ID","IDN"})
  // aadd(_O001, {"ˆ€, ˆ‘‹€Œ‘Š€Ÿ …‘“‹ˆŠ€","364",stod(""),stod(""),"IR","IRN"})
  // aadd(_O001, {"ˆ€Š","368",stod(""),stod(""),"IQ","IRQ"})
  // aadd(_O001, {"ˆ‹€„ˆŸ","372",stod(""),stod(""),"IE","IRL"})
  // aadd(_O001, {"ˆ‡€ˆ‹œ","376",stod(""),stod(""),"IL","ISR"})
  // aadd(_O001, {"ˆ’€‹ˆŸ","380",stod(""),stod(""),"IT","ITA"})
  // aadd(_O001, {"Š’ „`ˆ‚“€","384",stod(""),stod(""),"CI","CIV"})
  // aadd(_O001, {"ŸŒ€‰Š€","388",stod(""),stod(""),"JM","JAM"})
  // aadd(_O001, {"ŸˆŸ","392",stod(""),stod(""),"JP","JPN"})
  // aadd(_O001, {"Š€‡€•‘’€","398",stod(""),stod(""),"KZ","KAZ"})
  // aadd(_O001, {"ˆ„€ˆŸ","400",stod(""),stod(""),"JO","JOR"})
  // aadd(_O001, {"Š…ˆŸ","404",stod(""),stod(""),"KE","KEN"})
  // aadd(_O001, {"Š…Ÿ, €„-„…ŒŠ€’ˆ—…‘Š€Ÿ …‘“‹ˆŠ€","408",stod(""),stod(""),"KP","PRK"})
  // aadd(_O001, {"Š…Ÿ, …‘“‹ˆŠ€","410",stod(""),stod(""),"KR","KOR"})
  // aadd(_O001, {"Š“‚…‰’","414",stod(""),stod(""),"KW","KWT"})
  // aadd(_O001, {"Šˆƒˆ‡ˆŸ","417",stod(""),stod(""),"KG","KGZ"})
  // aadd(_O001, {"‹€‘‘Š€Ÿ €„-„…ŒŠ€’ˆ—…‘Š€Ÿ …‘“‹ˆŠ€","418",stod(""),stod(""),"LA","LAO"})
  // aadd(_O001, {"‹ˆ‚€","422",stod(""),stod(""),"LB","LBN"})
  // aadd(_O001, {"‹…‘’","426",stod(""),stod(""),"LS","LSO"})
  // aadd(_O001, {"‹€’‚ˆŸ","428",stod(""),stod(""),"LV","LVA"})
  // aadd(_O001, {"‹ˆ…ˆŸ","430",stod(""),stod(""),"LR","LBR"})
  // aadd(_O001, {"‹ˆ‚ˆŸ","434",stod(""),stod(""),"LY","LBY"})
  // aadd(_O001, {"‹ˆ•’…˜’…‰","438",stod(""),stod(""),"LI","LIE"})
  // aadd(_O001, {"‹ˆ’‚€","440",stod(""),stod(""),"LT","LTU"})
  // aadd(_O001, {"‹Š‘…Œ“ƒ","442",stod(""),stod(""),"LU","LUX"})
  // aadd(_O001, {"Œ€Š€","446",stod(""),stod(""),"MO","MAC"})
  // aadd(_O001, {"Œ€„€ƒ€‘Š€","450",stod(""),stod(""),"MG","MDG"})
  // aadd(_O001, {"Œ€‹€‚ˆ","454",stod(""),stod(""),"MW","MWI"})
  // aadd(_O001, {"Œ€‹€‰‡ˆŸ","458",stod(""),stod(""),"MY","MYS"})
  // aadd(_O001, {"Œ€‹œ„ˆ‚›","462",stod(""),stod(""),"MV","MDV"})
  // aadd(_O001, {"Œ€‹ˆ","466",stod(""),stod(""),"ML","MLI"})
  // aadd(_O001, {"Œ€‹œ’€","470",stod(""),stod(""),"MT","MLT"})
  // aadd(_O001, {"Œ€’ˆˆŠ€","474",stod(""),stod(""),"MQ","MTQ"})
  // aadd(_O001, {"Œ€‚ˆ’€ˆŸ","478",stod(""),stod(""),"MR","MRT"})
  // aadd(_O001, {"Œ€‚ˆŠˆ‰","480",stod(""),stod(""),"MU","MUS"})
  // aadd(_O001, {"Œ…Š‘ˆŠ€","484",stod(""),stod(""),"MX","MEX"})
  // aadd(_O001, {"Œ€Š","492",stod(""),stod(""),"MC","MCO"})
  // aadd(_O001, {"Œƒ‹ˆŸ","496",stod(""),stod(""),"MN","MNG"})
  // aadd(_O001, {"Œ‹„‚€, …‘“‹ˆŠ€","498",stod(""),stod(""),"MD","MDA"})
  // aadd(_O001, {"—…ƒˆŸ","499",stod(""),stod(""),"ME","MNE"})
  // aadd(_O001, {"Œ’‘…€’","500",stod(""),stod(""),"MS","MSR"})
  // aadd(_O001, {"Œ€ŠŠ","504",stod(""),stod(""),"MA","MAR"})
  // aadd(_O001, {"Œ‡€ŒˆŠ","508",stod(""),stod(""),"ŒZ","MOZ"})
  // aadd(_O001, {"Œ€","512",stod(""),stod(""),"OM","OMN"})
  // aadd(_O001, {"€ŒˆˆŸ","516",stod(""),stod(""),"NA","NAM"})
  // aadd(_O001, {"€““","520",stod(""),stod(""),"NR","NRU"})
  // aadd(_O001, {"…€‹","524",stod(""),stod(""),"NP","NPL"})
  // aadd(_O001, {"ˆ„…‹€„›","528",stod(""),stod(""),"NL","NLD"})
  // aadd(_O001, {"Š€‘€","531",stod(""),stod(""),"CW","CUW"})
  // aadd(_O001, {"€“€","533",stod(""),stod(""),"AW","ABW"})
  // aadd(_O001, {"‘…-Œ€’… (­¨¤¥à« ­¤áª ï ç áâì)","534",stod(""),stod(""),"SX","SXM"})
  // aadd(_O001, {"‰, ‘ˆ’-‘’€’ˆ“‘ ˆ ‘€€","535",stod(""),stod(""),"BQ","BES"})
  // aadd(_O001, {"‚€Ÿ Š€‹…„ˆŸ","540",stod(""),stod(""),"NC","NCL"})
  // aadd(_O001, {"‚€“€’“","548",stod(""),stod(""),"VU","VUT"})
  // aadd(_O001, {"‚€Ÿ ‡…‹€„ˆŸ","554",stod(""),stod(""),"NZ","NZL"})
  // aadd(_O001, {"ˆŠ€€ƒ“€","558",stod(""),stod(""),"NI","NIC"})
  // aadd(_O001, {"ˆƒ…","562",stod(""),stod(""),"NE","NER"})
  // aadd(_O001, {"ˆƒ…ˆŸ","566",stod(""),stod(""),"NG","NGA"})
  // aadd(_O001, {"ˆ“","570",stod(""),stod(""),"NU","NIU"})
  // aadd(_O001, {"‘’‚ ”‹Š","574",stod(""),stod(""),"NF","NFK"})
  // aadd(_O001, {"‚…ƒˆŸ","578",stod(""),stod(""),"NO","NOR"})
  // aadd(_O001, {"‘…‚…›… Œ€ˆ€‘Šˆ… ‘’‚€","580",stod(""),stod(""),"MP","MNP"})
  // aadd(_O001, {"Œ€‹›… ’ˆ•Š…€‘Šˆ… ’„€‹…›… ‘’‚€ ‘…„ˆ…›• ˜’€’‚","581",stod(""),stod(""),"UM","UMI"})
  // aadd(_O001, {"ŒˆŠ…‡ˆŸ, ”…„…€’ˆ‚›… ˜’€’›","583",stod(""),stod(""),"FM","FSM"})
  // aadd(_O001, {"Œ€˜€‹‹‚› ‘’‚€","584",stod(""),stod(""),"MH","MHL"})
  // aadd(_O001, {"€‹€“","585",stod(""),stod(""),"PW","PLW"})
  // aadd(_O001, {"€Šˆ‘’€","586",stod(""),stod(""),"PK","PAK"})
  // aadd(_O001, {"€€Œ€","591",stod(""),stod(""),"PA","PAN"})
  // aadd(_O001, {"€“€-‚€Ÿ ƒ‚ˆ…Ÿ","598",stod(""),stod(""),"PG","PNG"})
  // aadd(_O001, {"€€ƒ‚€‰","600",stod(""),stod(""),"PY","PRY"})
  // aadd(_O001, {"…“","604",stod(""),stod(""),"PE","PER"})
  // aadd(_O001, {"”ˆ‹ˆˆ›","608",stod(""),stod(""),"PH","PHL"})
  // aadd(_O001, {"ˆ’Š…","612",stod(""),stod(""),"PN","PCN"})
  // aadd(_O001, {"‹œ˜€","616",stod(""),stod(""),"PL","POL"})
  // aadd(_O001, {"’“ƒ€‹ˆŸ","620",stod(""),stod(""),"PT","PRT"})
  // aadd(_O001, {"ƒ‚ˆ…Ÿ-ˆ‘€“","624",stod(""),stod(""),"GW","GNB"})
  // aadd(_O001, {"’ˆŒ-‹…‘’…","626",stod(""),stod(""),"TL","TLS"})
  // aadd(_O001, {"“’-ˆŠ","630",stod(""),stod(""),"PR","PRI"})
  // aadd(_O001, {"Š€’€","634",stod(""),stod(""),"QA","QAT"})
  // aadd(_O001, {"…œ","638",stod(""),stod(""),"RE","REU"})
  // aadd(_O001, {"“Œ›ˆŸ","642",stod(""),stod(""),"RO","ROU"})
  // aadd(_O001, {"‘‘ˆŸ","643",stod(""),stod(""),"RU","RUS"})
  // aadd(_O001, {"“€„€","646",stod(""),stod(""),"RW","RWA"})
  // aadd(_O001, {"‘…-€’…‹…Œˆ","652",stod(""),stod(""),"BL","BLM"})
  // aadd(_O001, {"‘‚Ÿ’€Ÿ …‹…€, ‘’‚ ‚‡…‘…ˆŸ, ’ˆ‘’€-„€-Š“œŸ","654",stod(""),stod(""),"SH","SHN"})
  // aadd(_O001, {"‘…’-Šˆ’‘ ˆ …‚ˆ‘","659",stod(""),stod(""),"KN","KNA"})
  // aadd(_O001, {"€ƒˆ‹œŸ","660",stod(""),stod(""),"AI","AIA"})
  // aadd(_O001, {"‘…’-‹‘ˆŸ","662",stod(""),stod(""),"LC","LCA"})
  // aadd(_O001, {"‘…-Œ€’…","663",stod(""),stod(""),"MF","MAF"})
  // aadd(_O001, {"‘…’-œ… ˆ ŒˆŠ…‹","666",stod(""),stod(""),"PM","SPM"})
  // aadd(_O001, {"‘…’-‚ˆ‘…’ ˆ ƒ…€„ˆ›","670",stod(""),stod(""),"VC","VCT"})
  // aadd(_O001, {"‘€-Œ€ˆ","674",stod(""),stod(""),"SM","SMR"})
  // aadd(_O001, {"‘€-’Œ… ˆ ˆ‘ˆˆ","678",stod(""),stod(""),"ST","STP"})
  // aadd(_O001, {"‘€“„‚‘Š€Ÿ €€‚ˆŸ","682",stod(""),stod(""),"SA","SAU"})
  // aadd(_O001, {"‘……ƒ€‹","686",stod(""),stod(""),"SN","SEN"})
  // aadd(_O001, {"‘…ˆŸ","688",stod(""),stod(""),"RS","SRB"})
  // aadd(_O001, {"‘…‰˜…‹›","690",stod(""),stod(""),"SC","SYC"})
  // aadd(_O001, {"‘œ…€-‹……","694",stod(""),stod(""),"SL","SLE"})
  // aadd(_O001, {"‘ˆƒ€“","702",stod(""),stod(""),"SG","SGP"})
  // aadd(_O001, {"‘‹‚€ŠˆŸ","703",stod(""),stod(""),"SK","SVK"})
  // aadd(_O001, {"‚œ…’€Œ","704",stod(""),stod(""),"VN","VNM"})
  // aadd(_O001, {"‘‹‚…ˆŸ","705",stod(""),stod(""),"SI","SVN"})
  // aadd(_O001, {"‘Œ€‹ˆ","706",stod(""),stod(""),"SO","SOM"})
  // aadd(_O001, {"†€Ÿ €”ˆŠ€","710",stod(""),stod(""),"ZA","ZAF"})
  // aadd(_O001, {"‡ˆŒ€‚…","716",stod(""),stod(""),"ZW","ZWE"})
  // aadd(_O001, {"ˆ‘€ˆŸ","724",stod(""),stod(""),"ES","ESP"})
  // aadd(_O001, {"‡€€„€Ÿ ‘€•€€","732",stod(""),stod(""),"EH","ESH"})
  // aadd(_O001, {"†›‰ ‘“„€","728",stod(""),stod(""),"SS","SSD"})
  // aadd(_O001, {"‘“„€","729",stod(""),stod(""),"SD","SDN"})
  // aadd(_O001, {"‘“ˆ€Œ","740",stod(""),stod(""),"SR","SUR"})
  // aadd(_O001, {"˜ˆ–…ƒ… ˆ Ÿ Œ€‰…","744",stod(""),stod(""),"SJ","SJM"})
  // aadd(_O001, {"‘‚€‡ˆ‹…„","748",stod(""),stod(""),"SZ","SWZ"})
  // aadd(_O001, {"˜‚…–ˆŸ","752",stod(""),stod(""),"SE","SWE"})
  // aadd(_O001, {"˜‚…‰–€ˆŸ","756",stod(""),stod(""),"CH","CHE"})
  // aadd(_O001, {"‘ˆˆ‰‘Š€Ÿ €€‘Š€Ÿ …‘“‹ˆŠ€","760",stod(""),stod(""),"SY","SYR"})
  // aadd(_O001, {"’€„†ˆŠˆ‘’€","762",stod(""),stod(""),"TJ","TJK"})
  // aadd(_O001, {"’€ˆ‹€„","764",stod(""),stod(""),"TH","THA"})
  // aadd(_O001, {"’ƒ","768",stod(""),stod(""),"TG","TGO"})
  // aadd(_O001, {"’Š…‹€“","772",stod(""),stod(""),"TK","TKL"})
  // aadd(_O001, {"’ƒ€","776",stod(""),stod(""),"TO","TON"})
  // aadd(_O001, {"’ˆˆ„€„ ˆ ’€ƒ","780",stod(""),stod(""),"TT","TTO"})
  // aadd(_O001, {"š…„ˆ…›… €€‘Šˆ… Œˆ€’›","784",stod(""),stod(""),"AE","ARE"})
  // aadd(_O001, {"’“ˆ‘","788",stod(""),stod(""),"TN","TUN"})
  // aadd(_O001, {"’“–ˆŸ","792",stod(""),stod(""),"TR","TUR"})
  // aadd(_O001, {"’“ŠŒ…ˆŸ","795",stod(""),stod(""),"TM","TKM"})
  // aadd(_O001, {"‘’‚€ ’…Š‘ ˆ Š€‰Š‘","796",stod(""),stod(""),"TC","TCA"})
  // aadd(_O001, {"’“‚€‹“","798",stod(""),stod(""),"TV","TUV"})
  // aadd(_O001, {"“ƒ€„€","800",stod(""),stod(""),"UG","UGA"})
  // aadd(_O001, {"“Š€ˆ€","804",stod(""),stod(""),"UA","UKR"})
  // aadd(_O001, {"…‘“‹ˆŠ€ Œ€Š…„ˆŸ","807",stod(""),stod(""),"MK","MKD"})
  // aadd(_O001, {"…ƒˆ…’","818",stod(""),stod(""),"EG","EGY"})
  // aadd(_O001, {"‘…„ˆ…… Š‹…‚‘’‚","826",stod(""),stod(""),"GB","GBR"})
  // aadd(_O001, {"ƒ…‘ˆ","831",stod(""),stod(""),"GG","GGY"})
  // aadd(_O001, {"„†…‘ˆ","832",stod(""),stod(""),"JE","JEY"})
  // aadd(_O001, {"‘’‚ Œ","833",stod(""),stod(""),"IM","IMN"})
  // aadd(_O001, {"’€‡€ˆŸ, š…„ˆ…€Ÿ …‘“‹ˆŠ€","834",stod(""),stod(""),"TZ","TZA"})
  // aadd(_O001, {"‘…„ˆ…›… ˜’€’›","840",stod(""),stod(""),"US","USA"})
  // aadd(_O001, {"‚ˆƒˆ‘Šˆ… ‘’‚€, ‘˜€","850",stod(""),stod(""),"VI","VIR"})
  // aadd(_O001, {"“Šˆ€-”€‘","854",stod(""),stod(""),"BF","BFA"})
  // aadd(_O001, {"““ƒ‚€‰","858",stod(""),stod(""),"UY","URY"})
  // aadd(_O001, {"“‡…Šˆ‘’€","860",stod(""),stod(""),"UZ","UZB"})
  // aadd(_O001, {"‚……‘“‹€, ‹ˆ‚€ˆ€‘Š€Ÿ …‘“‹ˆŠ€","862",stod(""),stod(""),"VE","VEN"})
  // aadd(_O001, {"“‹‹ˆ‘ ˆ ”“’“€","876",stod(""),stod(""),"WF","WLF"})
  // aadd(_O001, {"‘€Œ€","882",stod(""),stod(""),"WS","WSM"})
  // aadd(_O001, {"‰…Œ…","887",stod(""),stod(""),"YE","YEM"})
  // aadd(_O001, {"‡€ŒˆŸ","894",stod(""),stod(""),"ZM","ZMB"})
  // aadd(_O001, {"€•€‡ˆŸ","895",stod(""),stod(""),"AB","ABH"})
  // aadd(_O001, {"†€Ÿ ‘…’ˆŸ","896",stod(""),stod(""),"OS","OST"})
  endif

  return _O001

* 21.02.21 ¢¥à­ãâì áâà ­ã
Function getCountry(lstrana)
  Static kod_RF := '643'

  Local s := space(10), i

  if !empty(lstrana) .and. lstrana != kod_RF ;
         .and. (i := ascan(glob_O001, {|x| x[2] == lstrana })) > 0
    s := glob_O001[i,1]
  endif
  return s
  
